version: "3.7"

services:
  db:
    image: mysql:8.0
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --general-log=true
      --general-log-file=/var/log/mysql/general.log
    environment:
      - MYSQL_DATABASE=ogp
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=default
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"